#!/bin/bash
# Script de diagnostic pour les boutons "Ajouter au panier"

echo "🔍 DIAGNOSTIC - Boutons Panier (Produits Similaires)"
echo "======================================================"
echo ""
echo "📋 INSTRUCTIONS DE TEST:"
echo ""
echo "1. Ouvrir la page produit dans le navigateur"
echo "   http://127.0.0.1:8000/produit/X/"
echo ""
echo "2. Ouvrir la Console Développeur (F12)"
echo "   Onglet: Console"
echo ""
echo "3. Descendre à 'Vous pourriez aussi aimer'"
echo ""
echo "4. Cliquer sur un bouton '🛒 Ajouter'"
echo ""
echo "5. OBSERVER dans la Console:"
echo ""
echo "   ✅ SI SUCCÈS, vous devriez voir:"
echo "      'Ajout au panier - URL: /panier/ajouter/XX/'"
echo "      'Réponse reçue, status: 200'"
echo "      'Données reçues: {success: true, ...}'"
echo ""
echo "   ❌ SI ERREUR, vous verrez l'une de ces lignes:"
echo ""
echo "      A. 'HTTP error! status: 404'"
echo "         → L'URL est incorrecte"
echo "         → Vérifier l'URL pattern dans boutique/urls.py"
echo ""
echo "      B. 'HTTP error! status: 403'"
echo "         → Problème CSRF token"
echo "         → Vérifier les cookies dans Onglet 'Application'"
echo ""
echo "      C. 'Données reçues: {success: false, ...}'"
echo "         → Le serveur a rejeté la demande"
echo "         → Vérifier le stock du produit"
echo "         → Voir le terminal Django pour les logs"
echo ""
echo "      D. 'SyntaxError: Unexpected token'"
echo "         → La réponse n'est pas du JSON valide"
echo "         → Vérifier que la vue retourne JsonResponse"
echo ""
echo "📊 VÉRIFICATIONS ADDITIONNELLES:"
echo ""
echo "Dans la Console (F12 > Console), exécuter:"
echo ""
echo "// 1. Vérifier les boutons"
echo "document.querySelectorAll('.btn-quick-add')"
echo "// Devrait afficher NodeList avec les boutons"
echo ""
echo "// 2. Vérifier le CSRF token"
echo "document.cookie.match('csrftoken=([^;]+)')"
echo "// Devrait afficher le token"
echo ""
echo "// 3. Tester manuellement l'URL"
echo "fetch('/panier/ajouter/1/', {"
echo "  method: 'POST',"
echo "  headers: {"
echo "    'X-CSRFToken': document.cookie.match('csrftoken=([^;]+)')[1]"
echo "  }"
echo "}).then(r => r.json()).then(console.log)"
echo ""
echo "🔧 CORRECTIONS POSSIBLES:"
echo ""
echo "Si l'URL est 404:"
echo "  → Vérifier dans boutique/urls.py:"
echo "     path('panier/ajouter/<int:produit_id>/', ...)"
echo ""
echo "Si CSRF error:"
echo "  → Vider le cache du navigateur"
echo "  → Rafraîchir la page (Ctrl+F5)"
echo ""
echo "Si success: false:"
echo "  → Vérifier le stock du produit dans l'admin"
echo "  → Regarder le terminal Django pour le message d'erreur"
echo ""
echo "📝 LOGS DU SERVEUR:"
echo "Dans le terminal où Django tourne, observer:"
echo "  [XX/Oct/2025 HH:MM:SS] \"POST /panier/ajouter/XX/ HTTP/1.1\" 200 XXX"
echo "  Status 200 = Succès"
echo "  Status 404 = URL non trouvée"
echo "  Status 403 = CSRF error"
echo ""
