#!/bin/bash
# Script pour tester la comparaison améliorée

echo "🔄 Redémarrage du serveur Django pour charger les nouveaux templatetags..."
echo ""
echo "⚠️  INSTRUCTIONS:"
echo "1. Arrêtez le serveur actuel avec Ctrl+C"
echo "2. Puis exécutez cette commande:"
echo ""
echo "   cd /home/ahmadmbow/e-commerce/ecommerce && python3 manage.py runserver"
echo ""
echo "3. Ensuite testez la comparaison:"
echo "   - Allez sur http://127.0.0.1:8000/boutique/"
echo "   - Ajoutez 2-3 produits à la comparaison"
echo "   - Cliquez sur 'Comparer'"
echo ""
echo "✅ Vérifications à faire:"
echo "   - Le badge '🏆 Meilleur choix' apparaît sur une colonne"
echo "   - Les promotions affichent '-X FCFA (-Y%)'"
echo "   - Le stock est affiché avec des codes couleur"
echo "   - Le rapport qualité/prix est calculé"
echo "   - Les cases vertes mettent en évidence les meilleures valeurs"
echo ""
echo "📝 Fichiers modifiés:"
echo "   ✓ templates/boutique/compare.html (interface)"
echo "   ✓ boutique/views.py (algorithme de scoring)"
echo "   ✓ boutique/templatetags/boutique_filters.py (nouveaux filtres)"
echo ""
