#!/bin/bash
# Test du bouton "Ajouter au panier" dans les produits similaires

echo "🧪 TEST - Bouton Ajouter au Panier (Produits Similaires)"
echo "============================================================"
echo ""
echo "✅ CORRECTION APPLIQUÉE:"
echo "   Fichier: templates/boutique/produit_detail.html"
echo "   Ligne: 836-838"
echo "   Problème: body dupliqué dans fetch()"
echo "   Status: CORRIGÉ ✓"
echo ""
echo "📋 ÉTAPES DE TEST:"
echo ""
echo "1. Redémarrer le serveur (si ce n'est pas déjà fait):"
echo "   Ctrl + C (dans le terminal du serveur)"
echo "   python3 manage.py runserver"
echo ""
echo "2. Accéder à une page produit:"
echo "   http://127.0.0.1:8000/produit/1/"
echo "   (Remplacer '1' par l'ID d'un produit existant)"
echo ""
echo "3. Descendre jusqu'à 'Vous pourriez aussi aimer'"
echo ""
echo "4. Cliquer sur le bouton '🛒 Ajouter' d'un produit similaire"
echo ""
echo "✅ RÉSULTAT ATTENDU:"
echo "   ✓ Toast vert apparaît: 'Produit ajouté au panier !'"
echo "   ✓ Compteur du panier s'incrémente dans la navbar"
echo "   ✓ Bouton affiche '✓ Ajouté !' pendant 1.5s"
echo "   ✓ Bouton revient à '🛒 Ajouter' après"
echo ""
echo "❌ SI PROBLÈME:"
echo "   1. Ouvrir la console du navigateur (F12)"
echo "   2. Onglet 'Console' pour voir les erreurs JavaScript"
echo "   3. Onglet 'Network' pour voir la requête POST"
echo "   4. Vérifier que l'URL est correcte: /ajouter-au-panier/X/"
echo ""
echo "📊 DEBUGGING:"
echo "   Dans la console du navigateur (F12 > Console):"
echo "   > document.querySelectorAll('.btn-quick-add')"
echo "   Devrait afficher les boutons trouvés"
echo ""
echo "🎯 NOTE:"
echo "   Les boutons sont désactivés si le produit est en rupture de stock"
echo "   Le texte change alors en 'Indisponible'"
echo ""
