# Generated by Django 5.2.5 on 2025-08-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_remove_produit_stock_produit_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='note',
            field=models.FloatField(default=0.0),
        ),
    ]
