# Generated by Django 5.2.5 on 2025-08-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_categorie_produit_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.AddField(
            model_name='produit',
            name='categories',
            field=models.ManyToManyField(related_name='produits', to='boutique.categorie'),
        ),
    ]
