# Generated by Django 5.2.5 on 2025-09-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0008_commande_commandeitem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='icon',
            field=models.CharField(default='fas fa-folder', max_length=50),
        ),
    ]
