# Generated by Django 5.2.5 on 2025-09-17 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0009_categorie_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='note',
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.categorie'),
        ),
    ]
