# Generated by Django 5.2.5 on 2025-09-17 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0010_remove_produit_categories_remove_produit_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boutique.categorie'),
            preserve_default=False,
        ),
    ]
