# Generated by Django 5.2.5 on 2025-09-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0012_remove_produit_categorie_produit_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('LIVREUR', 'Livreur'), ('ADMIN', 'Administrateur')], default='CLIENT', editable=False, max_length=20),
        ),
    ]
