# Generated by Django 5.2.5 on 2025-09-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0014_alter_userprofile_photo_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('LIVREUR', 'Livreur'), ('STAFF', 'Staff')], default='CLIENT', max_length=20),
        ),
    ]
