# Generated by Django 5.2.5 on 2025-09-24 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0016_alter_panieritem_options_panieritem_date_ajout_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('destinataire', models.CharField(max_length=150)),
                ('ligne1', models.CharField(max_length=255)),
                ('ligne2', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('code_postal', models.CharField(blank=True, max_length=20)),
                ('pays', models.CharField(default='Sénégal', max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
