# Generated by Django 5.2.5 on 2025-09-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0017_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
