# Generated by Django 5.2.5 on 2025-09-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0018_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_gps',
            field=models.TextField(blank=True, help_text='Adresse récupérée via GPS', null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
