# Generated by Django 5.2.5 on 2025-09-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0019_commande_adresse_gps_commande_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='latitude',
            new_name='latitude_client',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='longitude',
            new_name='longitude_client',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='adresse_gps',
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse_gps_client',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='derniere_maj_position',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='latitude_livreur',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='longitude_livreur',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='precision_gps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
