# Generated by Django 5.2.5 on 2025-09-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0020_rename_latitude_commande_latitude_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='adresse_gps_client',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='latitude_client',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='longitude_client',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='precision_gps',
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse_gps',
            field=models.TextField(blank=True, help_text='Adresse formatée via géocodage inverse', null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
