# Generated by Django 5.2.7 on 2025-10-06 02:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0021_remove_commande_adresse_gps_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='distance_km',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='tarif_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.CreateModel(
            name='AvisLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('commentaire', models.TextField(blank=True)),
                ('date_avis', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to=settings.AUTH_USER_MODEL)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_recus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('livreur', 'client')},
            },
        ),
    ]
