# Generated by Django 5.2.7 on 2025-10-06 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0023_avisproduit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adresse',
            options={'ordering': ['-is_default', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='panieritem',
            options={},
        ),
        migrations.RemoveField(
            model_name='commande',
            name='adresse_gps',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='derniere_maj_position',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='latitude_livreur',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='longitude_livreur',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='tarif_livraison',
        ),
        migrations.AddField(
            model_name='commande',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_livrees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avislivreur',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes_livreur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avislivreur',
            name='livreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_recus_livreur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
