# Generated by Django 4.2.11 on 2025-10-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0025_adresse_latitude_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_gps',
            field=models.CharField(blank=True, help_text='Adresse GPS ou texte brut', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude GPS du client', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude GPS du client', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='destinataire',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
