# Generated by Django 5.2.7 on 2025-10-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0026_commande_adresse_gps_commande_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
