# Generated by Django 5.2.7 on 2025-10-16 13:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0027_produit_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours'), ('RESOLU', 'Résolu'), ('FERME', 'Fermé')], default='NOUVEAU', max_length=20)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=20)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('lu', models.BooleanField(default=False)),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_support', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Support',
                'verbose_name_plural': 'Messages Support',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ReponseSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_reponse', models.DateTimeField(default=django.utils.timezone.now)),
                ('est_admin', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='boutique.messagesupport')),
            ],
            options={
                'verbose_name': 'Réponse Support',
                'verbose_name_plural': 'Réponses Support',
                'ordering': ['date_reponse'],
            },
        ),
    ]
