# Generated by Django 5.2.7 on 2025-10-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0028_messagesupport_reponsesupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='avislivreur',
            name='examine',
            field=models.BooleanField(default=False, help_text="Marqué comme examiné par l'administrateur"),
        ),
        migrations.AddField(
            model_name='avisproduit',
            name='examine',
            field=models.BooleanField(default=False, help_text="Marqué comme examiné par l'administrateur"),
        ),
    ]
