# Generated by Django 5.2.7 on 2025-10-16 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0029_avislivreur_examine_avisproduit_examine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAdminVue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('NOUVEAU_CLIENT', 'Nouveau Client'), ('NOUVELLE_COMMANDE', 'Nouvelle Commande'), ('NOUVEAU_MESSAGE', 'Nouveau Message'), ('NOUVEL_AVIS', 'Nouvel Avis'), ('RUPTURE_STOCK', 'Rupture de Stock')], max_length=30)),
                ('objet_id', models.IntegerField(help_text="ID de l'objet concerné (User, Commande, etc.)")),
                ('date_vue', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_vues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Admin Vue',
                'verbose_name_plural': 'Notifications Admin Vues',
                'ordering': ['-date_vue'],
                'unique_together': {('admin', 'type_notification', 'objet_id')},
            },
        ),
    ]
