# Generated by Django 5.2.7 on 2025-12-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0031_commandeinvite_commandeinviteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationadminvue',
            name='type_notification',
            field=models.CharField(choices=[('NOUVEAU_CLIENT', 'Nouveau Client'), ('NOUVELLE_COMMANDE', 'Nouvelle Commande'), ('NOUVEAU_MESSAGE', 'Nouveau Message'), ('AVIS_PRODUIT', 'Avis Produit'), ('AVIS_LIVREUR', 'Avis Livreur'), ('RUPTURE_STOCK', 'Rupture de Stock')], max_length=30),
        ),
    ]
