# Generated by Django 5.2.7 on 2025-12-05 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0033_messagesupport_nom_visiteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='boutique.adresse'),
        ),
        migrations.AlterField(
            model_name='notificationadminvue',
            name='type_notification',
            field=models.CharField(choices=[('NOUVEAU_CLIENT', 'Nouveau Client'), ('NOUVELLE_COMMANDE', 'Nouvelle Commande'), ('NOUVELLE_COMMANDE_INVITE', 'Nouvelle Commande Invité'), ('NOUVEAU_MESSAGE', 'Nouveau Message'), ('AVIS_PRODUIT', 'Avis Produit'), ('AVIS_LIVREUR', 'Avis Livreur'), ('RUPTURE_STOCK', 'Rupture de Stock')], max_length=30),
        ),
    ]
