# Generated by Django 5.2.7 on 2025-12-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0034_add_adresse_to_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, help_text='Image de la catégorie', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-folder', max_length=50, null=True),
        ),
    ]
