# Generated by Django 5.2.7 on 2025-12-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0035_add_image_to_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur du véhicule'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modèle du véhicule'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Immatriculation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type de véhicule'),
        ),
    ]
