# Generated by Django 5.2.7 on 2025-12-08 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0036_userprofile_vehicle_color_userprofile_vehicle_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Taille',
                'verbose_name_plural': 'Tailles',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='a_tailles',
            field=models.BooleanField(default=False, help_text='Cocher si ce produit est disponible en plusieurs tailles'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock total (somme des stocks par taille si tailles actives)'),
        ),
        migrations.AlterUniqueTogether(
            name='panieritem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commandeinviteitem',
            name='taille',
            field=models.ForeignKey(blank=True, help_text='Taille sélectionnée pour ce produit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.taille'),
        ),
        migrations.AddField(
            model_name='commandeitem',
            name='taille',
            field=models.ForeignKey(blank=True, help_text='Taille sélectionnée pour ce produit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.taille'),
        ),
        migrations.AddField(
            model_name='panieritem',
            name='taille',
            field=models.ForeignKey(blank=True, help_text='Taille sélectionnée pour ce produit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.taille'),
        ),
        migrations.AlterUniqueTogether(
            name='panieritem',
            unique_together={('user', 'produit', 'taille')},
        ),
        migrations.CreateModel(
            name='ProduitTaille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_tailles', to='boutique.produit')),
                ('taille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_tailles', to='boutique.taille')),
            ],
            options={
                'verbose_name': 'Stock par taille',
                'verbose_name_plural': 'Stocks par taille',
                'ordering': ['taille__ordre'],
                'unique_together': {('produit', 'taille')},
            },
        ),
    ]
